import { format } from 'date-fns'
import Head from 'next/head'
import { useRouter } from 'next/router'
import React from 'react'
import Footer from '../components/Footer'
import Header from '../components/Header'
import InfoCard from '../components/InfoCard'
import Map from '../components/Map'

const Search = ({searchResults}) => {
    const router = useRouter();
    const {location, startDate, endDate, numberOfGuests} = router.query;

    const formatStartDate = format(new Date(startDate), "dd MMMM yy");
    const formatEndDate = format(new Date(endDate), "dd MMMM yy");
    const range = `${formatStartDate} - ${formatEndDate}`;
    
    return (
        <div>
            <Head>
                <title>Next.js Airbnb - Search</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header placeholder={`${location} | ${range} | ${numberOfGuests} guests`} />
            <main className="flex">
                <section className="flex-grow pt-14 px-6">
                    <p className="text-sm">300+ Stays - {range} - for {numberOfGuests} guests</p>
                    <h1 className="text-3xl font-semibold mt-2 mb-6">Stays in {location}</h1>
                    <div className="hidden lg:inline-flex mb-5 space-x-3 text-gray-800 whitespace-nowrap">
                        <p className="button">Cancellation Flexibility</p>
                        <p className="button">Type of Place</p>
                        <p className="button">Price</p>
                        <p className="button">Rooms and Beds</p>
                        <p className="button">More Filters</p>
                    </div>
                    <div className="flex flex-col">
                        {searchResults?.map(({img, location, title, description, star, price, total, long, lat}) => (
                            <InfoCard key={Math.random()} img={img} location={location} title={title} description={description} star={star} price={price} total={total} long={long} lat={lat} />
                        ))}
                    </div>
                </section>
                <section className="hidden xl:inline-flex xl:min-w-[600px]">
                    <Map searchResults={searchResults} />
                </section>
            </main>
            <Footer />
        </div>
    )
}

export default Search

export async function getServerSideProps() {
    const searchResults = await fetch("https://links.papareact.com/isz").
    then(res => res.json());

    return {
        props: {
            searchResults
        }
    }
}